{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range $key, $value := .Values.imagePullSecrets }}
  - name: {{ $value.name }}
{{- end }}
metadata:
  name: {{ include "go-heptabase.serviceAccountName" . }}
  labels:
    {{- include "go-heptabase.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
